Action:

#攻擊顯示數字(向上)
#Attack display damage (up)
#-------------------------------------------------------------------------#
- Action[a=AttackDisplayUp] ~onAttack

#攻擊顯示數字(向上) (暴擊)
#Attack display damage (up)(Critical)
#-------------------------------------------------------------------------#
- Action[a=AttackDisplayUpCrit] ~onCrit

#攻擊顯示數字(向上) (魔法)
#Attack display damage (up)(Magic)
#-------------------------------------------------------------------------#
- Action[a=AttackDisplayUp] ~onMagic

#攻擊顯示數字(向上) (魔法暴擊)
#Attack display damage (up)(Magic Critical)
#-------------------------------------------------------------------------#
- Action[a=AttackDisplayUpCrit] ~onMCrit

#攻擊顯示數字(向上) (失敗)
#Attack display damage (up)(Fail)
#-------------------------------------------------------------------------#
- Action[a=AttackDisplayUpMiss] ~onAtkMiss

#打開範例GUI
#Open the sample GUI
#-------------------------------------------------------------------------#
- Action[a=OpenExpGui] ~onCommand



#-------------------------------------------------------------------------#



