#
#火
Sword_Non:
  Material: 'Wooden_Sword'
  Data:
  CustomModelData: 0
  HideItemFlags: true
  DisplayName: '§e無屬性的劍'
  Lore:
  - ''
  - '§7屬性 : 無'
  Attributes:
    Name: '移除原本屬性用'
    Inherit: 'GENERIC_ATTACK_DAMAGE'
    Operation: 'ADD_NUMBER'
    Amount: 0.1
    EquipmentSlot: 'HAND'
#
Sword_Non:
  Material: 'Wooden_Sword'
  Data:
  CustomModelData: 0
  HideItemFlags: true
  DisplayName: '§e無屬性的劍'
  Lore:
  - ''
  - '§7屬性 : 無'
  Attributes:
    Name: '移除原本屬性用'
    Inherit: 'GENERIC_ATTACK_DAMAGE'
    Operation: 'ADD_NUMBER'
    Amount: 0.1
    EquipmentSlot: 'HAND'

Deputy:
  Material: 'Diamond_Leggings'
  Data:
  CustomModelData: 0
  RemoveItemFlags: true
  DisplayName: '§e體質副手'
  Lore:
  - ''
  - '§7體質: 20'

arms:
  Material: 'BOOK'
  Data:
  CustomModelData: 0
  RemoveItemFlags: true
  DisplayName: '§e體質武器'
  Lore:
  - '§e受到特定體型的目標攻擊時，降低受到此體型目標的傷害'
  - ''
  - '§7體質: 1'
  Enchantments:
  - DAMAGE_ALL:5
  - KNOCKBACK:2
  - FIRE_ASPECT:2
  Attributes:
    Name: '加速書'
    Inherit: 'GENERIC_MOVEMENT_SPEED'
    Operation: 'ADD_NUMBER'
    Amount: 0.2
    EquipmentSlot: 'OFF_HAND'