#語言(英語,繁體中文,簡體中文)
#Language (English,Chinese_TW,Chinese_CN,Portuguese_BR)
Language: English

#傷害判斷的核心插件. (Default,MMOLib,MMOCore,AttributePlus,SkillAPI,SkillAPI_MMOLib)
#The core plugin for damage judgment. (Default,MMOLib,MMOCore,AttributePlus,SkillAPI,SkillAPI_MMOLib)
AttackCore: Default