#目前只能在Default設定.
#Currently it can only be set in Default.
Action:

#攻擊顯示傷害(向上)
#-------------------------------------------------------------------------#
- Action[mark=&target_uuid&EntityTopDisplayMonster;stop=true] ~onDeath
- Action[mark=&target_uuid&EntityTopDisplayAnimal;stop=true] ~onDeath
- Action[mark=&target_uuid&EntityTopDisplayPlayer;stop=true] ~onDeath
