#目前只能在Default設定.
#Currently it can only be set in Default.
Action:

#攻擊顯示傷害(向上)
#-------------------------------------------------------------------------#
- Action[mark=&target_uuid&EntityTopDisplayMonster;stop=true] ~onDeath

- Action[mark=&target_uuid&EntityTopDisplayAnimal;stop=true] ~onDeath

- Action[mark=&target_uuid&EntityTopDisplayPlayer;stop=true] ~onDeath

- Action[mark=%player_name%BoosBarDisplay;stop=true] ~onDeath

- Action[mark=&target_uuid&NameDisplayAttackMonster;stop=true] ~onDeath

- Action[mark=&target_uuid&NameDisplayAttackAnimal;stop=true] ~onDeath