#目前只能在Default設定.
#Currently it can only be set in Default.
Action:

#被攻擊顯示傷害(向上)
#Being attacked shows damage (up)
#-------------------------------------------------------------------------#

- Action[a=DamagedDisplayUp] ~onDamaged

#死亡清除標記動作
#Death clear mark action
#-------------------------------------------------------------------------#
- Action[mark=&target_uuid&EntityTopDisplayMonster;stop=true] ~onDeath

- Action[mark=&target_uuid&EntityTopDisplayAnimal;stop=true] ~onDeath

- Action[mark=&target_uuid&EntityTopDisplayPlayer;stop=true] ~onDeath

- Action[mark=&target_uuid&NameDisplayAttackMonster;stop=true] ~onDeath

- Action[mark=&target_uuid&NameDisplayAttackAnimal;stop=true] ~onDeath