Buttons:

  PlayerTotal:
    RawSlot: 0
    Move: false
    Material: 'COAL'
    CustomModelData: 496
    RemoveItemFlags: true
    Name: '§e回到總覽'
    Lore:
    - ''
    Left:
    - Action[a=Open_Gui_Player_Total]

  Close:
    Move: false
    Material: 'COAL'
    CustomModelData: 497
    RemoveItemFlags: true
    Name: '§e關閉視窗'
    Lore:
    - ''
    Left:
    - Action[a=Close_Gui]












