#
#
Buttons:

  Stats:
    RawSlot: 15
    Move: true
    Material: 'PLAYER_HEAD'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '§e&self_name&'
    Lore:
    - ''
    - '§7職業: §c&self_class_name&'
    - ''
    - '§7Base等級: §e&self_level_now_base& / &self_level_max_base&'
    - '§7Job等級: §e&self_level_now_job& / &self_level_max_job&'
    - '§7Bas經驗值: §e&self_exp_now_base& / &self_exp_max_base&'
    - '§7Job經驗值: §e&self_exp_now_job& / &self_exp_max_job&'
    - ''
    - '§7屬性點: §6&self_point_last_base& / &self_point_max_base&'
    - '§7技能點: §6&self_point_last_job& / &self_point_max_job&'
    Left:
    - Action[a=EmojiHelpHD2;mark=&self_name&]
    Right:
    - Action[a=EmojiHelpHD2;mark=&self_name&]
    
  Str:
    RawSlot: 23
    Move: true
    Material: 'RED_DYE'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '力量'
    Lore:
    - ''
    - '目前力量: §c§l&self_attr_point_str&'
    - ''
    - '⚔ 攻擊力: §c&self_attr_stats_melee_physical_attack&'
    - ''
    - '§e左擊加點'
    - '§e右擊減點'
    Left:
    - Action[a=add_Attributes_Str;mark=&self_name&]
    Right:
    - Action[a=cut_Attributes_Str;mark=&self_name&]
    
  Agi:
    RawSlot: 24
    Move: true
    Material: 'LEATHER_BOOTS'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '敏捷'
    Lore:
    - ''
    - '目前敏捷: §c§l&self_attr_point_agi&'
    - ''
    - '§e左擊加點'
    - '§e右擊減點'
    Left:
    - Action[a=add_Attributes_Agi;mark=&self_name&]
    Right:
    - Action[a=cut_Attributes_Agi;mark=&self_name&]

  Vit:
    RawSlot: 25
    Move: true
    Material: 'DIAMOND_CHESTPLATE'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '體質'
    Lore:
    - ''
    - '目前體質: §c§l&self_attr_point_vit&'
    - ''
    - '§e左擊加點'
    - '§e右擊減點'
    Left:
    - Action[a=add_Attributes_Vit;mark=&self_name&]
    Right:
    - Action[a=cut_Attributes_Vit;mark=&self_name&]

  Int:
    RawSlot: 32
    Move: true
    Material: 'BOOK'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '智力'
    Lore:
    - ''
    - '目前智力: §c§l&self_attr_point_int&'
    - ''
    - '§e左擊加點'
    - '§e右擊減點'
    Left:
    - Action[a=add_Attributes_Int;mark=&self_name&]
    Right:
    - Action[a=cut_Attributes_Int;mark=&self_name&]

  Dex:
    RawSlot: 33
    Move: true
    Material: 'ARROW'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '靈巧'
    Lore:
    - ''
    - '目前靈巧: §c§l&self_attr_point_dex&'
    - ''
    - '§e左擊加點'
    - '§e右擊減點'
    Left:
    - Action[a=add_Attributes_Dex;mark=&self_name&]
    Right:
    - Action[a=cut_Attributes_Dex;mark=&self_name&]

  Luk:
    RawSlot: 34
    Move: true
    Material: 'NETHER_STAR'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '幸運'
    Lore:
    - ''
    - '目前幸運: §c§l&self_attr_point_luk&'
    - ''
    - '§e左擊加點'
    - '§e右擊減點'
    Left:
    - Action[a=add_Attributes_Luk;mark=&self_name&]
    Right:
    - Action[a=cut_Attributes_Luk;mark=&self_name&]





