#
#
Buttons:

  Stats:
    RawSlot: 4
    Move: false
    Material: 'PLAYER_HEAD'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '§e&self_name&'
    Lore:
    - ''
    - '§7職業: §9&self_class_name&&self_Eq_Fire_Attack&'
    - ''
    - '§7Base等級: §e&self_level_now_base& / &self_level_max_base&'
    - '§7Bas經驗值: §e&self_exp_now_base& / &self_exp_max_base&'
    - '§7Job等級: §e&self_level_now_job& / &self_level_max_job&'
    - '§7Job經驗值: §e&self_exp_now_job& / &self_exp_max_job&'
    - ''
    - '§7屬性點: §6&self_point_last_base& / &self_point_max_base&'
    - '§7技能點: §6&self_point_last_job& / &self_point_max_job&'
    Left:
    - Action[a=EmojiHelpHD2;mark=&self_name&]
    Right:
    - Action[a=EmojiHelpHD2;mark=&self_name&]
    
  Str:
    RawSlot: 12
    Move: false
    Material: 'RED_DYE'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '§e力量'
    Lore:
    - ''
    - '目前力量: §9§l&self_attr_point_str&'
    - ''
    - '§e左擊加點'
    - '§e右擊減點'
    Left:
    - Action[a=add_Attributes_Str;mark=&self_name&]
    Right:
    - Action[a=cut_Attributes_Str;mark=&self_name&]
    
  Agi:
    RawSlot: 13
    Move: false
    Material: 'LEATHER_BOOTS'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '§e敏捷'
    Lore:
    - ''
    - '目前敏捷: §9§l&self_attr_point_agi&'
    - ''
    - '§e左擊加點'
    - '§e右擊減點'
    Left:
    - Action[a=add_Attributes_Agi;mark=&self_name&]
    Right:
    - Action[a=cut_Attributes_Agi;mark=&self_name&]

  Vit:
    RawSlot: 14
    Move: false
    Material: 'DIAMOND_CHESTPLATE'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '§e體質'
    Lore:
    - ''
    - '目前體質: §9§l&self_attr_point_vit& + &self_Eq_Vit&'
    - ''
    - '§e左擊加點'
    - '§e右擊減點'
    Left:
    - Action[a=add_Attributes_Vit;mark=&self_name&]
    Right:
    - Action[a=cut_Attributes_Vit;mark=&self_name&]

  Int:
    RawSlot: 21
    Move: false
    Material: 'BOOK'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '§e智力'
    Lore:
    - ''
    - '目前智力: §9§l&self_attr_point_int&'
    - ''
    - '§e左擊加點'
    - '§e右擊減點'
    Left:
    - Action[a=add_Attributes_Int;mark=&self_name&]
    Right:
    - Action[a=cut_Attributes_Int;mark=&self_name&]

  Dex:
    RawSlot: 22
    Move: false
    Material: 'ARROW'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '§e靈巧'
    Lore:
    - ''
    - '目前靈巧: §9§l&self_attr_point_dex&'
    - ''
    - '§e左擊加點'
    - '§e右擊減點'
    Left:
    - Action[a=add_Attributes_Dex;mark=&self_name&]
    Right:
    - Action[a=cut_Attributes_Dex;mark=&self_name&]

  Luk:
    RawSlot: 23
    Move: false
    Material: 'NETHER_STAR'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '§e幸運'
    Lore:
    - ''
    - '目前幸運: §9§l&self_attr_point_luk&'
    - ''
    - '§e左擊加點'
    - '§e右擊減點'
    Left:
    - Action[a=add_Attributes_Luk;mark=&self_name&]
    Right:
    - Action[a=cut_Attributes_Luk;mark=&self_name&]


  Stats0:
    RawSlot: 27
    Move: false
    Material: 'BOOK'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '§e基礎屬性總攬'
    Lore:
    - ''
    - '§7HP: §9&self_nowhealth&/&self_maxhealth&'
    - '§7HP恢復: §9&self_Hp_Regeneration&'
    - '§7物理攻擊: §9&self_Melee_Physical_Attack&'
    - '§7物理防禦: §9&self_melee_Physical_Defense&'
    - '§7命中: §9&self_Hit_Rate&'
    - '§7閃避: §9&self_Dodge_Rate&'

  Stats1:
    RawSlot: 28
    Move: false
    Material: 'BOOK'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '§e基礎屬性總攬'
    Lore:
    - ''
    - '§7SP: §9&self_Sp&'
    - '§7SP恢復: §9&self_Sp_Regeneration&'
    - '§7魔法攻擊: §9&self_Magic_Attack&'
    - '§7魔法防禦: §9&self_Magic_Defense&'
    - '§7移動速度: §9&self_Moving_Speed& §7%'
    - '§7攻擊速度: §9&self_Attack_Speed& §7%'

  Stats2:
    RawSlot: 29
    Move: false
    Material: 'BOOK'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '§e穿透、暴擊、吟唱'
    Lore:
    - ''
    - '§7物理穿透: §9&self_Physical_Penetration%& §7%'
    - '§7暴擊率: §9&self_Critical_Strike_Chance%& §7%'
    - '§7暴擊傷害: §9&self_Critical_Strike_Power%& §7%'
    - '§7暴擊防護: §9&self_Critical_Strike_Protection%& §7%'
    - '§7暴傷減免: §9&self_Critical_Strike_Reduction%& §7%'
    - '§7吟唱減免: §9&self_Cooldown_Reduction&'
    - '§7受治療加成: §9&self_Receive_Healing_Bonus%& §7%'
    - '§7治療加成: §9&self_Healing_Bonus%& §7%'

  Stats3:
    RawSlot: 30
    Move: false
    Material: 'BOOK'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '§e物理屬性'
    Lore:
    - ''
    - '§7物理攻擊%: §9&self_Physical_Attack%& §7%'
    - '§7物理防禦%: §9&self_Physical_Defense%& §7%'
    - '§7物傷加成%: §9&self_Physical_Damage_Bonus%& §7%'
    - '§7忽視物防%: §9&self_Ignore_Physical_Defense%& §7%'
    - '§7物傷減免%: §9&self_Physical_Injury_Reduction%& §7%'
    - '§7精煉物攻: §9&self_Refined_Physical_Attack&'
    - '§7精煉物免%: §9&self_Refined_Material_Free%& §7%'

  Stats4:
    RawSlot: 31
    Move: false
    Material: 'BOOK'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '§e魔法屬性'
    Lore:
    - ''
    - '§7魔法攻擊%: §9&self_Magic_Attack%& §7%'
    - '§7魔法防禦%: §9&self_Magic_Defense%& §7%'
    - '§7魔傷加成%: §9&self_Magic_Injury_Bonus%& §7%'
    - '§7忽視魔防%: §9&self_Ignore_Magic_Defense%& §7%'
    - '§7魔傷減免%: §9&self_Magic_Injury_Reduction%& §7%'
    - '§7精煉魔攻: §9&self_Refining_Magic_Attack&'
    - '§7精煉魔免%: §9&self_Refining_Magic_Free%& §7%'


  Stats5:
    RawSlot: 32
    Move: false
    Material: 'BOOK'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '§e狀態抵抗和攻擊'
    Lore:
    - '§e受異常狀態時，減少影響機率和時長'
    - '§e添加異常狀態時，提高生效率和時長'
    - ''
    - '§7中毒抵抗%: §9&self_Poisoning_Resistance%& §7%'
    - '§7流血抵抗%: §9&self_Bleeding_Resistance%& §7%'
    - '§7灼燒抵抗%: §9&self_Burning_Resistance%& §7%'
    - '§7暈眩抵抗%: §9&self_Dizziness_Resistance%& §7%'
    - '§7冰凍抵抗%: §9&self_Freezing_Resistance%& §7%'
    - '§7石化抵抗%: §9&self_Petrochemical_Resistance%& §7%'
    - '§7睡眠抵抗%: §9&self_Sleep_Resistance%& §7%'
    - '§7恐懼抵抗%: §9&self_Fear_Resistance%& §7%'
    - '§7定身抵抗%: §9&self_Fixed_Resistance%& §7%'
    - '§7沉默抵抗%: §9&self_Silent_Resistance%& §7%'
    - '§7詛咒抵抗%: §9&self_Curse_Resistance%& §7%'
    - '§7黑暗抵抗%: §9&self_Dark_Resistance%& §7%'

  Stats6:
    RawSlot: 33
    Move: false
    Material: 'BOOK'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '§e屬性-技能增強'
    Lore:
    - '§e增強自身屬性技能的攻擊強度'
    - ''
    - '§7無屬性攻擊%: §9&self_No_Attribute_Attack%& §7%'
    - '§7火屬性攻擊%: §9&self_Fire_Attribute_Attack%& §7%'
    - '§7地屬性攻擊%: §9&self_Geological_Attribute_Attack%& §7%'
    - '§7水屬性攻擊%: §9&self_Water_Attribute_Attack%& §7%'
    - '§7風屬性攻擊%: §9&self_Wind_Attribute_Attack%& §7%'
    - '§7毒屬性攻擊%: §9&self_Poison_Attribute_Attack%& §7%'
    - '§7不死屬性攻擊%: §9&self_Immortality_Attribute_Attack%& §7%'
    - '§7暗屬性攻擊%: §9&self_Dark_Attribute_Attack%& §7%'
    - '§7聖屬性攻擊%: §9&self_Holy_Attribute_Attack%& §7%'
    - '§7念屬性攻擊%: §9&self_Sense_Attribute_Attack%& §7%'

  Stats7:
    RawSlot: 34
    Move: false
    Material: 'BOOK'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '§e屬性-攻擊增加'
    Lore:
    - '§e攻擊對應屬性的目標時，提高對此屬性生物的傷害'
    - ''
    - '§7對無屬性魔物增傷%: §9&self_Increase_Damage_To_Non_Attribute_monsters%& §7%'
    - '§7對火屬性魔物增傷%: §9&self_Increase_Damage_To_Fire_Attribute_monsters%& §7%'
    - '§7對地屬性魔物增傷%: §9&self_Increase_Damage_To_Earth_Attribute_monsters%& §7%'
    - '§7對水屬性魔物增傷%: §9&self_Increase_Damage_To_Water_Attribute_monsters%& §7%'
    - '§7對風屬性魔物增傷%: §9&self_Increase_Damage_To_Wind_Attribute_monsters%& §7%'
    - '§7對毒屬性魔物增傷%: §9&self_Increase_Damage_To_Poisonous_Attribute_monsters%& §7%'
    - '§7對不死屬性魔物增傷%: §9&self_Increase_Damage_To_Undead_Attribute_monsters%& §7%'
    - '§7對暗屬性魔物增傷%: §9&self_Increase_Damage_To_Dark_Attribute_monsters%& §7%'
    - '§7對聖屬性魔物增傷%: §9&self_Increase_Damage_To_Holy_Attribute_monsters%& §7%'
    - '§7對念屬性魔物增傷%: §9&self_Increase_Damage_To_Mind_Attribute_monsters%& §7%'

  Stats8:
    RawSlot: 35
    Move: false
    Material: 'BOOK'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '§e屬性-傷害減免'
    Lore:
    - '§e受到屬性傷害時，降低受到此屬性的傷害'
    - ''
    - '§7對無屬性傷害減免%: §9&self_No_Attribute_Damage_Reduction%& §7%'
    - '§7對火屬性傷害減免%: §9&self_Fire_Attribute_Damage_Reduction%& §7%'
    - '§7對地屬性傷害減免%: §9&self_Earth_Attribute_Damage_Reduction%& §7%'
    - '§7對水屬性傷害減免%: §9&self_Water_Attribute_Damage_Reduction%& §7%'
    - '§7對風屬性傷害減免%: §9&self_Wind_Attribute_Damage_Reduction%& §7%'
    - '§7對毒屬性傷害減免%: §9&self_Poison_Attribute_Damage_Reduction%& §7%'
    - '§7對不死屬性傷害減免%: §9&self_Undead_Attribute_Damage_Reduction%& §7%'
    - '§7對暗屬性傷害減免%: §9&self_Dark_Attribute_Damage_Reduction%& §7%'
    - '§7對聖屬性傷害減免%: §9&self_Holy_Attribute_Damage_Reduction%& §7%'
    - '§7對念屬性傷害減免%: §9&self_Mind_Attribute_Damage_Reduction%& §7%'


  Stats9:
    RawSlot: 36
    Move: false
    Material: 'BOOK'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '§e種族-攻擊增加'
    Lore:
    - '§e對特定種族的目標攻擊時，提高對此種族的傷害效果'
    - ''
    - '§7對無形增傷%: §9&self_Increases_Damage_To_Invisible%& §7%'
    - '§7對植物增傷%: §9&self_Increases_Damage_To_Plant%& §7%'
    - '§7對昆蟲增傷%: §9&self_Increases_Damage_To_Insect%& §7%'
    - '§7對動物增傷%: §9&self_Increases_Damage_To_Animal%& §7%'
    - '§7對魚貝增傷%: §9&self_Increases_Damage_To_Fish%& §7%'
    - '§7對人形增傷%: §9&self_Increases_Damage_To_Human%& §7%'
    - '§7對不死增傷%: §9&self_Increases_Damage_To_Immortal%& §7%'
    - '§7對龍族增傷%: §9&self_Increases_Damage_To_Dragon%& §7%'
    - '§7對天使增傷%: §9&self_Increases_Damage_To_Angel%& §7%'
    - '§7對惡魔增傷%: §9&self_Increases_Damage_To_Demon%& §7%'


  Stats10:
    RawSlot: 37
    Move: false
    Material: 'BOOK'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '§e種族-傷害減免'
    Lore:
    - '§e受到特定種族的目標攻擊時，降低受到此種族目標的傷害'
    - ''
    - '§7對無形減傷%: §9&self_Reduce_Damage_To_Invisible%& §7%'
    - '§7對植物減傷%: §9&self_Reduce_Damage_To_Plant%& §7%'
    - '§7對昆蟲減傷%: §9&self_Reduce_Damage_To_Insect%& §7%'
    - '§7對動物減傷%: §9&self_Reduce_Damage_To_Animal%& §7%'
    - '§7對魚貝減傷%: §9&self_Reduce_Damage_To_Fish%& §7%'
    - '§7對人形減傷%: §9&self_Reduce_Damage_To_Human%& §7%'
    - '§7對不死減傷%: §9&self_Reduce_Damage_To_Immortal%& §7%'
    - '§7對龍族減傷%: §9&self_Reduce_Damage_To_Dragon%& §7%'
    - '§7對天使減傷%: §9&self_Reduce_Damage_To_Angel%& §7%'
    - '§7對惡魔減傷%: §9&self_Reduce_Damage_To_Demon%& §7%'


  Stats11:
    RawSlot: 38
    Move: false
    Material: 'BOOK'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '§e體型-攻擊增強'
    Lore:
    - '§e攻擊特定體型目標時，提高造成的傷害'
    - ''
    - '§7對小體型增傷%: §9&self_Increases_Damage_To_Small_Body%& §7%'
    - '§7對中體型增傷%: §9&self_Increases_Damage_To_Mid_Body%& §7%'
    - '§7對大體型增傷%: §9&self_Increases_Damage_To_Big_Body%& §7%'

  Stats12:
    RawSlot: 39
    Move: false
    Material: 'BOOK'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '§e體型-傷害減免'
    Lore:
    - '§e受到特定體型的目標攻擊時，降低受到此體型目標的傷害'
    - ''
    - '§7對小體型減傷%: §9&self_Reduce_Damage_To_Small_Body%& §7%'
    - '§7對中體型減傷%: §9&self_Reduce_Damage_To_Mid_Body%& §7%'
    - '§7對大體型減傷%: §9&self_Reduce_Damage_To_Big_Body%& §7%'

  Stats54:
    RawSlot: 53
    Move: true
    Material: 'BOOK'
    CustomModelData: 0
    RemoveItemFlags: true
    Name: '§e體質武器'
    Lore:
    - '§e受到特定體型的目標攻擊時，降低受到此體型目標的傷害'
    - ''
    - '§7體質: 1'



